version: '3.8'
services:
  app:
    build: .
    container_name: dataimpulse_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=dataimpulse
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: dataimpulse_db
    environment:
      MYSQL_DATABASE: dataimpulse
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
